config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  # De ahora en adelante, las urls serán '/check'
  root 'checks#index'
  resources :checks, only: %i[create update]
  # De ahora en adelante, las urls serán '/home'
  resources :home, only: [:index]

  # De ahora en adelante, las urls serán '/user'
  resources :users
  # De ahora en adelante, las urls serán '/company'
  resources :companies

  # De ahora en adelante, las urls serán '/reports'
  resources :reports, only: [:index]
  get '/reports/month', to: 'reports#monthly'
  get '/reports/day', to: 'reports#daily'
  get '/reports/absence', to: 'reports#absence'
end

app/models/admin.rb
# frozen_string_literal: true

# Class Admin
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# Class ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/check.rb
# frozen_string_literal: true

# Class Check
class Check < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
end

app/models/company.rb
# frozen_string_literal: true

# Class Company
class Company < ApplicationRecord
  has_many :users
  validates :name, presence: true, length: { minimum: 1 }, uniqueness: true
  validates :address, presence: true, length: { minimum: 1 }
end

app/models/user.rb
# frozen_string_literal: true

# Class User
class User < ApplicationRecord
  belongs_to :company
  has_many :checks
  validates :name, presence: true, length: { minimum: 10 }
  validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/, uniqueness: true
  validates :position, presence: true, length: { minimum: 10 }
  validates :emp_num, presence: true, length: { minimum: 6, maximum: 8 }, uniqueness: true
  validates :private_num, presence: true, length: { minimum: 6, maximum: 8 }
  validates :company_id, presence: true
  validates :status, presence: true
end

app/controllers/Admins/confirmations_controller.rb
# frozen_string_literal: true

module Admins
  class ConfirmationsController < Devise::ConfirmationsController
  end
end

app/controllers/Admins/passwords_controller.rb
# frozen_string_literal: true

module Admins
  class PasswordsController < Devise::PasswordsController
  end
end

app/controllers/Admins/registrations_controller.rb
# frozen_string_literal: true

module Admins
  class RegistrationsController < Devise::RegistrationsController
  end
end

app/controllers/Admins/sessions_controller.rb
# frozen_string_literal: true

module Admins
  # Class SessionController
  class SessionsController < Devise::SessionsController
    def after_sign_in_path_for(_resource)
      '/home'
    end
  end
end

app/controllers/Admins/unlocks_controller.rb
# frozen_string_literal: true

module Admins
  class UnlocksController < Devise::UnlocksController
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Class ApplicationController
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
# frozen_string_literal: true

# Class ChecksController
class ChecksController < ApplicationController
  def index
    nil
  end

  def create
    @user = User.find_by(user_params)
    if @user.nil?
      flash[:msg] = 'User not found'
    elsif @user.status == '1'
      @check = Check.new(check_params)
      @todayCheck = Check.find_by(date: Date.today, user_id: @user.id)
      case @check.check
      when '1'
        if @todayCheck
          flash[:msg] = 'You already checked in today'
        else
          @check.user_id = @user.id
          @check.date = Date.today
          @check.save
          flash[:msg] = 'Successfully check in'
        end
      when '2'
        if @todayCheck
          @todayCheck.update(check: '2')
          flash[:msg] = 'Successfully check out'
        else
          flash[:msg] = 'You have not checked in'
        end
      else
        flash[:msg] = 'You missed select an option'
      end
    else
      flash[:msg] = 'User Sleep'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def user_params
    params.permit(:emp_num, :private_num)
  end

  def check_params
    params.permit(:check)
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

# Class CompaniesController
class CompaniesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @companies = Company.order(:id)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path, status: :see_other
  end

  private

  def company_params
    params.require(:company).permit(:name, :address)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Class HomeController
class HomeController < ApplicationController
  before_action :authenticate_admin!
  def index; end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# Class ReportsController
class ReportsController < ApplicationController
  before_action :authenticate_admin!
  def index; end

  def monthly; end

  def daily
    @hours_in = Check.all.map { |record| record.created_at.hour }
    @avgin_hour = @hours_in.sum / @hours_in.count.to_f
    @hours_out = Check.all.map { |record| record.updated_at.hour }
    @avgout_hour = @hours_out.sum / @hours_out.count.to_f
  end

  def absence
    @users = User.order(:id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Class UserController
class UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.order(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    @user = User.find(params[:id])
    if @user.status == '1'
      @user.update(status: '0')
    else
      @user.update(status: '1')
    end
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :position, :private_num, :emp_num, :status, :company_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Module ApplicationHelper
module ApplicationHelper
end

app/helpers/checks_helper.rb
# frozen_string_literal: true

# Module ChecksHelper
module ChecksHelper
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

# Module CompaniesHelper 
module CompaniesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Module HomeHelper
module HomeHelper
end

app/helpers/login_helper.rb
# frozen_string_literal: true

# Module LoginHelper
module LoginHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

# Module ReportsHelper
module ReportsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Module UsersHelper
module UsersHelper
end

app/views/check/index.html.erb
<main class="main-container bg-first">
  <div class="m-auto">
      <div class="text-dark bg-light display-1 p-3 rounded text-center shadow">
        <span class="" id='hour'></span>
        <span class='red-dot'>:</span>
        <span id='min'></span><span class='red-dot'>:</span>
        <span id='second'></span>
      </div>
      <span id='titulo'></span>
    </div>
    <div class="mx-5 m-md-auto py-5 py-md-0">
      <div class="p-4 rounded shadow bg-light align-items-center ">
        <h1 class="display-3 text-center fw-bold">Clock Checker</h1>
        <%= render "form", check: @check %>
      </div>
    </div>
  </div>
</main>

app/views/checks/_form.html.erb
<%= form_with url: checks_path, method: :post, class: 'justify-content-center text-dark' do |form| %>
  <div class="my-3 d-flex flex-column">
    <%= form.label :emp_num, "ID", class: 'form-label' %>
    <%= form.text_field :emp_num, class: 'form-control'%>
  </div>

  <div class="my-3 d-flex flex-column">
    <%= form.label :private_num, 'Password', class: 'form-label' %>
    <%= form.password_field :private_num, class: 'form-control' %>
  </div>

  <div class="my-3 d-flex flex justify-content-evenly form-check py-3">
    <div>
      <%= form.radio_button :check, 1 ,class: 'form-check-input'%> Check In
    </div>
    <div>
      <%= form.radio_button :check, 2 ,class: 'form-check-input'%> Check Out
    </div>
  </div>

  <div class="my-3 d-flex justify-content-center">
    <%= form.submit 'Check', class: 'btn btn-outline-dark' %>
  </div>
<% end %>

app/views/checks/create.html.erb
<h1>Check#create</h1>
<p>Find me in app/views/check/create.html.erb</p>

app/views/checks/index.html.erb
<main class="main-container bg-first">
  <div class="m-auto">
      <div class="text-dark bg-light display-1 p-3 rounded text-center shadow">
        <span class="" id='hour'></span>
        <span class='red-dot'>:</span>
        <span id='min'></span><span class='red-dot'>:</span>
        <span id='second'></span>
      </div>
    </div>
    <div class="mx-5 m-md-auto py-5 py-md-0">
      <div class="p-4 rounded shadow bg-light align-items-center ">
        <h1 class="display-3 text-center fw-bold">Clock Checker</h1>
        <%= render "form", check: @check %>
        <div class="text-center">
          <% flash.each do |key, value| %>
            <div>
              <%= value %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
</main>

app/views/checks/update.html.erb
<h1>Check#update</h1>
<p>Find me in app/views/check/update.html.erb</p>

app/views/companies/_form.html.erb
<%= form_with class: 'row', model: @company do |form| %>
  <div class="my-3 d-flex flex-column">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Company's Name"%>
    <% @company.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column">
    <%= form.label :address, class: 'form-label' %>
    <%= form.text_field :address, class: 'form-control', placeholder: "Company's Address" %>
    <% @company.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex justify-content-center">
    <%= form.submit class: 'btn btn-outline-dark'%>
  </div>
<% end %>

app/views/companies/create.html.erb
<h1>Company#create</h1>
<p>Find me in app/views/company/create.html.erb</p>

app/views/companies/edit.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-md-auto mb-3">
      <h1 class="text-center my-3">Edit Company</h1>
      <p class="text-center">Edit company typing in the input's form.</p>
      <%= link_to "Return", "/companies/", class: "btn btn-outline-dark shadow" %>
    </div>
    <div class="m-md-auto mb-3 p-4 rounded shadow bg-light align-items-center">
      <%= render 'form', company: @company %>
    </div>
  </div>
</main>

app/views/companies/index.html.erb
<main class="bg-first">
  <div class="container-xl">
    <div class="text-center pt-4">
      <h1>Manage Companies</h1>
      <p>Create, read, update and delete companies.</p>
    </div>

    <div>
      <%= link_to "Create company", "/companies/new", class: 'btn btn-outline-dark  my-3' %>
      <div class = "table-responsive shadow">
        <table class="table border-bottom border-dark w-100 text-center mt-4 table-hover">
          <tr class="">
            <th>ID</th>
            <th>NAME</th>
            <th>ADDRESS</th>
            <th>EDIT</th>
            <th>DEMOLISH</th>
          </tr>
          <% @companies.each do |company|  %>
            <tr>
              <td><%= company.id %></td>
              <td><%= company.name %></td>
              <td><%= company.address %></td>
              <td><%= link_to "Edit", edit_company_path(company.id), class: 'btn btn-outline-dark' %></td>
              <td><%= link_to "Demolish", company_path(company), class: 'btn btn-outline-dark', data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/companies/new.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-auto">
      <h1 class="text-center my-3">Create Company</h1>
      <p class="text-center">Create a new company typing in the input's form.</p>
      <%= link_to "Return", "/companies/", class: "btn btn-outline-dark shadow" %>
    </div>
    <div class="m-md-auto mb-3 p-4 rounded shadow bg-light align-items-center">
      <%= render 'form', company: @company %>
    </div>
  </div>
</main>

app/views/companies/show.html.erb
<h1>Company#show</h1>
<p>Find me in app/views/company/show.html.erb</p>

app/views/companies/update.html.erb
<h1>Company#update</h1>
<p>Find me in app/views/company/update.html.erb</p>

app/views/company/_form.html.erb
<%= form_with class: 'row', model: @company do |form| %>
  <div class="my-3 d-flex flex-column">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', placeholder: "Company's Name"%>
  </div>

  <div class="my-3 d-flex flex-column">
    <%= form.label :address, class: 'form-label' %>
    <%= form.text_field :address, class: 'form-control', placeholder: "Company's Address" %>
  </div>

  <div class="my-3 d-flex justify-content-center">
    <%= form.submit class: 'btn btn-outline-dark'%>
  </div>
<% end %>

app/views/company/_form1.html.erb
<%= form_with model: @company do |form|  %>
  <div>
    <%= form.label :Name %><br>
    <%= form.text_field :title, placeholder: "Company's Name" %>
  </div>
  <div>
    <%= form.label :Address %><br>
    <%= form.text_field :body, placeholder: "Company's Address"%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/company/edit.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-md-auto mb-3">
      <h1 class="text-center my-3">Edit Company</h1>
      <p class="text-center">Edit company typing in the input's form.</p>
      <%= link_to "Return", "/company/", class: "btn btn-outline-dark shadow" %>
    </div>
    <div class="m-md-auto mb-3 p-4 rounded shadow bg-light align-items-center">
      <%= render 'form', company: @company %>
    </div>
  </div>
</main>

app/views/company/new.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-auto">
      <h1 class="text-center my-3">Create Company</h1>
      <p class="text-center">Create a new company typing in the input's form.</p>
      <%= link_to "Return", "/company/", class: "btn btn-outline-dark shadow" %>
    </div>
    <div class="m-md-auto mb-3 p-4 rounded shadow bg-light align-items-center">
      <%= render 'form', company: @company %>
    </div>
  </div>
</main>

app/views/user/edit.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-md-auto mb-3">
      <h1 class="text-center my-3">Edit Employee</h1>
      <p class="text-center">Edit a employee typing in the input's form.</p>
      <%= link_to "Return", "/user/", class: "btn btn-outline-dark shadow" %>
    </div>
    <div class="m-md-auto mb-3 p-4 rounded shadow bg-light align-items-center ">
      <%= render 'form', user: @user %>
    </div>
  </div>
</main>

app/views/user/new.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-md-auto mb-3">
      <h1 class="text-center my-3">Create Employee</h1>
      <p class="text-center">Create a new employee typing in the input's form.</p>
      <%= link_to "Return", "/user/", class: "btn btn-outline-dark" %>
    </div>
    <div class="m-auto p-4 rounded shadow bg-light align-items-center ">
      <%= render 'form', user: @user %>
    </div>
  </div>
</main>

app/views/users/_form.html.erb
<%= form_with class: 'row', model: @user do |form| %>
  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :name, class: 'form-label' %><br>
    <%= form.text_field :name, class: 'form-control' %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :email, class: 'form-label' %><br>
    <%= form.email_field :email, class: 'form-control' %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :position, class: 'form-label' %><br>
    <%= form.text_field :position, class: 'form-control' %>
    <% @user.errors.full_messages_for(:position).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :emp_num, class: 'form-label' %><br>
    <%= form.number_field :emp_num, step: 1, class: 'form-control' %>
    <% @user.errors.full_messages_for(:emp_num).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :private_num, class: 'form-label' %><br>
    <%= form.password_field :private_num, value: @user.private_num, step: 1, class: 'form-control' %>
    <% @user.errors.full_messages_for(:private_num).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :company_id, class: 'form-label' %><br>
    <%= form.select :company_id, Company.all.collect {|p| [p.name, p.id]}, include_blank: true, class: "form-select" %>
    <% @user.errors.full_messages_for(:company_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column col-md-6">
    <%= form.label :status, class: 'form-label' %><br>
    <%= form.select :status, [['Active', 1], ['Inactive', 0]], include_blank: true, class: "form-select"%>
    <% @user.errors.full_messages_for(:status).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="my-3 d-flex flex-column">
    <%= form.submit class: 'btn btn-outline-dark'%>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/edit.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-md-auto mb-3">
      <h1 class="text-center my-3">Edit Employee</h1>
      <p class="text-center">Edit a employee typing in the input's form.</p>
      <%= link_to "Return", "/users/", class: "btn btn-outline-dark shadow" %>
    </div>
    <div class="m-md-auto mb-3 p-4 rounded shadow bg-light align-items-center ">
      <%= render 'form', user: @user %>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main class="bg-first">
  <div class="container-xl">
    <div class="text-center pt-4">
      <h1>Manage Employees</h1>
      <p>Create, read, update user and sleep employee</p>
    </div>

    <div class = "">
      <%= link_to "Create user", "/users/new", class: 'btn btn-outline-dark shadow my-3' %>
      <div class = "table-responsive shadow" >
        <table class="table border-bottom border-dark w-100 text-center mt-4 table-hover">
          <tr class="">
            <th class = "">ID</th>
            <th>NAME</th>
            <th>EMAIL</th>
            <th>POSITION</th>
            <th>EMPLOYEE NUMBER</th>
            <th>PRIVATE NUMBER</th>
            <th>COMPANY</th>
            <th>STATUS</th>
            <th>EDIT</th>
            <th>SLEEP</th>
          </tr>
          <% @users.each do |user|  %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.position %></td>
            <td><%= user.emp_num %></td>
            <td><%= user.private_num %></td>
            <td><%= "#{user.company == nil ? "Sin Compañia": user.company.name }" %></td>
            <td><%= "#{user.status == '0' ? "Inactive" : 'Active'}" %></td>
            <td><%= link_to "Edit", edit_user_path(user.id), class: 'btn btn-outline-dark' %></td>
            <td><%= link_to "#{user.status == '1' ? "Sleep" : 'Activate'}", user_path(user), class: 'btn btn-outline-dark', data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<main class="bg-first">
  <div class="main-container container-xl h-100">
    <div class="d-flex flex-column justify-content-center align-items-center m-md-auto mb-3">
      <h1 class="text-center my-3">Create Employee</h1>
      <p class="text-center">Create a new employee typing in the input's form.</p>
      <%= link_to "Return", "/users/", class: "btn btn-outline-dark" %>
    </div>
    <div class="m-auto p-4 rounded shadow bg-light align-items-center ">
      <%= render 'form', user: @user %>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>